export const REVIEW_RULE_OPTIONS = [
  {
    label: "Shared rent money",
    category: "Shared rent contribution",
    ruleType: "shared_bill_contribution",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: false,
    helper: "Someone paying their share of rent. Excluded from income and used to reduce your rent burden.",
  },
  {
    label: "Shared bill money",
    category: "Shared bill contribution",
    ruleType: "shared_bill_contribution",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: false,
    helper: "Someone paying you back for a bill. Excluded from income and used to reduce your bill burden.",
  },
  {
    label: "Rent / housing",
    category: "Rent",
    isBill: true,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: true,
    helper: "Your rent, mortgage or landlord payment.",
  },
  {
    label: "Bill",
    category: "Major bill",
    isBill: true,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: true,
    helper: "A regular payment you need money ready for.",
  },
  {
    label: "Subscription",
    category: "Subscription",
    isBill: false,
    isSubscription: true,
    isInternalTransfer: false,
    matchAmount: true,
    helper: "Netflix, Apple, memberships, app plans, gyms or similar.",
  },
  {
    label: "Wages / income",
    category: "Wages",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: false,
    helper: "Pay from work, benefits, salary or reliable income.",
  },
  {
    label: "Normal purchase",
    category: "Spending",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: true,
    helper: "A normal shop, card payment or purchase. Counts as spending, not a bill.",
  },
  {
    label: "One-off payment",
    category: "One-off payment",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: true,
    helper: "A one-time outgoing that should count as spending but should not become a regular bill.",
  },
  {
    label: "Friend / family",
    category: "Personal payment",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: false,
    helper: "Gifts, lending, paying people back, or help from people you know.",
  },
  {
    label: "Work money",
    category: "Work / pass-through",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: false,
    helper: "Expenses, resale, client money or pass-through money that is not really yours to spend.",
  },
  {
    label: "Refund / paid back",
    category: "Refund",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: false,
    matchAmount: false,
    helper: "Refunds, chargebacks, cashback or money returned after spending.",
  },
  {
    label: "My own transfer",
    category: "Internal Transfer",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: true,
    matchAmount: false,
    helper: "Moving your own money between accounts, savings, pots or investments.",
  },
  {
    label: "Irrelevant / exclude",
    category: "Ignore from budget",
    isBill: false,
    isSubscription: false,
    isInternalTransfer: true,
    matchAmount: false,
    helper: "Not useful for your budget. Excluded from income, spending and bills.",
  },
];
